// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdzGkkRJ1jEggu29Pvyb-OkmhICzdoxBw',
    appId: '1:48251044369:web:a82dfa61ad81ae9bba27b0',
    messagingSenderId: '48251044369',
    projectId: 'aiit-2025-26',
    authDomain: 'aiit-2025-26.firebaseapp.com',
    databaseURL: 'https://aiit-2025-26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aiit-2025-26.firebasestorage.app',
    measurementId: 'G-LNHS51S4KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVGLlSqGxDNVmx5OYlQgYAE3Ez8UzTjEs',
    appId: '1:48251044369:android:be6b030eed4d5ea6ba27b0',
    messagingSenderId: '48251044369',
    projectId: 'aiit-2025-26',
    databaseURL: 'https://aiit-2025-26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aiit-2025-26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh86QmBnndvdkm7FX6gsM7mBNN3_lX0P0',
    appId: '1:48251044369:ios:eb783c6f989f48b1ba27b0',
    messagingSenderId: '48251044369',
    projectId: 'aiit-2025-26',
    databaseURL: 'https://aiit-2025-26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aiit-2025-26.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh86QmBnndvdkm7FX6gsM7mBNN3_lX0P0',
    appId: '1:48251044369:ios:eb783c6f989f48b1ba27b0',
    messagingSenderId: '48251044369',
    projectId: 'aiit-2025-26',
    databaseURL: 'https://aiit-2025-26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aiit-2025-26.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdzGkkRJ1jEggu29Pvyb-OkmhICzdoxBw',
    appId: '1:48251044369:web:ba7cf4e2f50ed7e0ba27b0',
    messagingSenderId: '48251044369',
    projectId: 'aiit-2025-26',
    authDomain: 'aiit-2025-26.firebaseapp.com',
    databaseURL: 'https://aiit-2025-26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aiit-2025-26.firebasestorage.app',
    measurementId: 'G-5ZCLGVQ1GY',
  );
}
